<?php

namespace AppBundle\Repository;

/**
 * CouleursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouleursRepository extends \Doctrine\ORM\EntityRepository
{
}
