<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * DeclinaisonTailleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeclinaisonTailleRepository extends EntityRepository
{


    public function findProduitsByTaille_Famille($idTaille, $idFamille){
        $queryBuilder = $this->createQueryBuilder('t');
        $queryBuilder->join('t.produit', 'p')
            ->addSelect('p')
            ->where($queryBuilder->expr()->eq('p.famille', ':idFamille'))
            ->andWhere($queryBuilder->expr()->eq('t.taille', ':idTaille'))
            ->setParameters(array('idFamille' => $idFamille, 'idTaille' => $idTaille))
        ;

        return $queryBuilder
            ->getQuery()
            ->getResult();
    }

    public function findProduitsFiltres($arrayTaille){

        $tailleSplit = explode(",", $arrayTaille);

        $queryBuilder = $this->createQueryBuilder('t');
        $queryBuilder->join('t.produit', 'p')
            ->addSelect('p');

        $id=0;
        $orX = $queryBuilder->expr()->orX();

        foreach ($tailleSplit as  $taille) {
            $orX->add($queryBuilder->expr()->eq('t.taille', ":taille_".$id));
            $queryBuilder->setParameter("taille_".$id, $taille);
            $id++;
        }
        
        $queryBuilder->andWhere($orX);

        return $queryBuilder
            ->getQuery()
            ->getResult();
    }
}
