<?php

namespace AppBundle\Repository;

/**
 * DeclinaisonTailleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeclinaisonTailleRepository extends \Doctrine\ORM\EntityRepository
{
}
