<?php

namespace AppBundle\Repository;

/**
 * DeclinaisonCouleurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeclinaisonCouleurRepository extends \Doctrine\ORM\EntityRepository
{
}
