<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * DetailsEthiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeclinaisonEthiqueRepository extends EntityRepository
{
    public function searchProduit($search)
    {
        $queryBuilder = $this->createQueryBuilder('de');
        $queryBuilder
            ->join('de.produit', 'p')
            ->join('de.pointEthique', 'pe')
            ->orWhere('pe.nomEthique LIKE :search')
            ->setParameter('search', '%' . $search . '%');

        return $queryBuilder ->getQuery()->getResult();

    }


}
