<?php

namespace AppBundle\Repository;

/**
 * DetailPanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailPanierRepository extends \Doctrine\ORM\EntityRepository
{
}
