<?php

namespace AppBundle\Repository;

/**
 * DetailsEthiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailsEthiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
