<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * FamilleGlobalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilleGlobalRepository extends EntityRepository
{
    public function findOther($idFamilleGlobale){

        $queryBuilder = $this->createQueryBuilder('fg');
        $queryBuilder->where($queryBuilder->expr()->neq('fg.id',':idFamilleGlobale'))
            ->setParameter('idFamilleGlobale', $idFamilleGlobale);
        return $queryBuilder
            ->getQuery()
            ->getResult();


//        $queryBuilder= $this->_em->createQuery('SELECT f.id, f.familleGlobal FROM AppBundle:FamilleGlobal f WHERE f.id NOT LIKE :idFamilleGlobal')
//            ->setParameter('idFamilleGlobal', $idFamilleGlobale);
//
//        return $queryBuilder
//            ->getResult();
    }

}
