<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * FamilleGlobalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilleGlobalRepository extends EntityRepository
{
    public function findOther($idFamilleGlobale){
        $queryBuilder = $this->createQueryBuilder('fg');
        $queryBuilder->where($queryBuilder->expr()->neq('fg.id',':idFamilleGlobale'))
            ->setParameter('idFamilleGlobale', $idFamilleGlobale);

        return $queryBuilder
            ->getQuery()
            ->getResult();

    }

}
