<?php

namespace AppBundle\Repository;

/**
 * FamillesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamillesRepository extends \Doctrine\ORM\EntityRepository
{
}
