<?php

namespace AppBundle\Repository;

/**
 * FamilleGlobalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilleGlobalRepository extends \Doctrine\ORM\EntityRepository
{
}
