<?php

namespace AppBundle\Repository;

/**
 * ClientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembresRepository extends \Doctrine\ORM\EntityRepository
{
}
