<?php

namespace AppBundle\Repository;

/**
 * TailleTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TailleTypeRepository extends \Doctrine\ORM\EntityRepository
{

}
