app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /users
    defaults:
        _format: json

membres:
    type: rest
    resource: AppBundle\Controller\MembresController

adresse:
    type: rest
    resource: AppBundle\Controller\AdresseController

commande:
    type: rest
    resource: AppBundle\Controller\CommandeController

#PAYS
pays:
    type: rest
    resource: AppBundle\Controller\PaysController

#VILLES
villes:
    type: rest
    resource: AppBundle\Controller\VillesController

#PRODUITS
produits:
    type: rest
    resource: AppBundle\Controller\ProduitsController

panier:
    type: rest
    resource: AppBundle\Controller\PanierController

wishlist:
    type: rest
    resource: AppBundle\Controller\WishlistController


search:
    type: rest
    resource: AppBundle\Controller\ProduitsController

images:
    type: rest
    resource: AppBundle\Controller\ImagesProduitController

#FOURNISSEURS
fournisseurs:
    type: rest
    resource: AppBundle\Controller\FournisseursController

#FAMILLES
familles:
    type: rest
    resource: AppBundle\Controller\FamillesController

famillesGlobales:
    type: rest
    resource: AppBundle\Controller\FamilleGlobalController

#TAILLE
tailles:
    type: rest
    resource: AppBundle\Controller\DeclinaisonTailleController

#ETHIQUE
ethique:
    type: rest
    resource: AppBundle\Controller\DeclinaisonEthiqueController


#COULEUR
couleurs:
    type: rest
    resource: AppBundle\Controller\CouleursController

#TAILLETYPE
tailleType:
    type: rest
    resource: AppBundle\Controller\TailleTypeController

tout:
    type: rest
    resource: AppBundle\Controller\ProduitsController

impactsethiques:
    type: rest
    resource: AppBundle\Controller\PointsEthiqueController