app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

#PAYS
pays:
    type: rest
    resource: AppBundle\Controller\PaysController


#VILLES
villes:
    type: rest
    resource: AppBundle\Controller\VillesController

#PRODUITS
produits:
    type: rest
    resource: AppBundle\Controller\ProduitsController