app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#PAYS
pays:
    type: rest
    resource: AppBundle\Controller\PaysController

#VILLES
villes:
    type: rest
    resource: AppBundle\Controller\VillesController

#PRODUITS
produits:
    type: rest
    resource: AppBundle\Controller\ProduitsController

#PRODUITSFEMMES
femmes:
    type: rest
    resource: AppBundle\Controller\ProduitsController

images:
    type: rest
    resource: AppBundle\Controller\ImagesProduitController


##PRODUITS
#produitsSexe:
#    type: rest
#    resource: AppBundle\Controller\ProduitsController
#
##PRODUITS
#produitsFamille:
#    type: rest
#    resource: AppBundle\Controller\ProduitsController

#FOURNISSEURS
fournisseurs:
    type: rest
    resource: AppBundle\Controller\FournisseursController

#FAMILES
familles:
    type: rest
    resource: AppBundle\Controller\FamillesController


#TAILLE
tailles:
    type: rest
    resource: AppBundle\Controller\DeclinaisonTailleController

#ETHIQUE
ethique:
    type: rest
    resource: AppBundle\Controller\DeclinaisonEthiqueController



#COULEUR
couleurs:
    type: rest
    resource: AppBundle\Controller\CouleursController


#TAILLETYPE
tailleType:
    type: rest
    resource: AppBundle\Controller\TailleTypeController


#DECLINAISON_TAILLE
#produitsTaille:
#    type: rest
#    resource: AppBundle\Controller\DeclinaisonTailleController


#DECLINAISON_TAILLE
#produitsTailleFamille:
#    type: rest
#    resource: AppBundle\Controller\DeclinaisonTailleController




tout:
    type: rest
    resource: AppBundle\Controller\ProduitsController


impactsethiques:
    type: rest
    resource: AppBundle\Controller\PointsEthiqueController




#FOS_USER

user:
    type: rest
    resource: AppBundle\Controller\ClientsController

admin:
    type: rest
    resource: AppBundle\Controller\ClientsController



fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile